### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by TheDevMinerTV**
I added or updated:
- Updated:
    - the README
    - the kernel module for kernel 4.18.8
- Added: 
    - mcm-build.sh for building for specific targets 
    - mcm-buildall-distcc.sh for building crosscompilers using distcc
    - newcpio module to generate a new cpio image / archive when making changes on the filesystem, instead of recompiling the kernel

### CODE REVIEW

**Comment by TheDevMinerTV** [comment]
Just ignore the toolchain-related commits 'cuz I removed the module later.

**Comment by landley** [comment]
Sorry for the delay, 18 commits at once put it on my todo list until the weekend.

I note I'm trying to merge mkroot into my toybox project (ala http://lists.landley.net/pipermail/toybox-landley.net/2018-July/009545.html) but at the start of the year I switched from a day job that stressed and exhausted me because it was a dying startup (brilliant technology if we could just get the funding to get it to market...) to a job that exhausts me because I'm sitting in a cubicle all day (an "open floor plan" on floor 6 of building 7).

I'm not quite sure, from a design perspective, where I want to take the external mkroot project. I'd be happy to hear your suggestions on this since you've shown so much interest. I described a little of the goals I'm working towards in the above thread...

**Comment by landley** [comment]
Sorry for the delay, 18 commits at once put it on my todo list until the weekend.

I note I'm trying to merge mkroot into my toybox project (ala http://lists.landley.net/pipermail/toybox-landley.net/2018-July/009545.html) but at the start of the year I switched from a day job that stressed and exhausted me because it was a dying startup (brilliant technology if we could just get the funding to get it to market...) to a job that exhausts me because I'm sitting in a cubicle all day (an "open floor plan" on floor 6 of building 7).

I'm not quite sure, from a design perspective, where I want to take the external mkroot project. I'd be happy to hear your suggestions on this since you've shown so much interest. I described a little of the goals I'm working towards in the above thread...

**Comment by landley** [comment]
Sorry for the delay, 18 commits at once put it on my todo list until the weekend.

I note I'm trying to merge mkroot into my toybox project (ala http://lists.landley.net/pipermail/toybox-landley.net/2018-July/009545.html) but at the start of the year I switched from a day job that stressed and exhausted me because it was a dying startup (brilliant technology if we could just get the funding to get it to market...) to a job that exhausts me because I'm sitting in a cubicle all day (an "open floor plan" on floor 6 of building 7).

I'm not quite sure, from a design perspective, where I want to take the external mkroot project. I'd be happy to hear your suggestions on this since you've shown so much interest. I described a little of the goals I'm working towards in the above thread...

**Comment by landley** [comment]
Sorry for the delay, 18 commits at once put it on my todo list until the weekend.

I note I'm trying to merge mkroot into my toybox project (ala http://lists.landley.net/pipermail/toybox-landley.net/2018-July/009545.html) but at the start of the year I switched from a day job that stressed and exhausted me because it was a dying startup (brilliant technology if we could just get the funding to get it to market...) to a job that exhausts me because I'm sitting in a cubicle all day (an "open floor plan" on floor 6 of building 7).

I'm not quite sure, from a design perspective, where I want to take the external mkroot project. I'd be happy to hear your suggestions on this since you've shown so much interest. I described a little of the goals I'm working towards in the above thread...

**Comment by TheDevMinerTV** [comment]
Do you want to also merge mcm into toybox for crosscompiling?
I think, you should add my scripts for mcm to toybox...
And that you weren't active is fully understandable and I still like your
efforts for the custom linux and android scene! Especially MKROOT!

Have a great Day, Tobias

Rob Landley <notifications@github.com> schrieb am Mo., 22. Okt. 2018, 01:18:

**Comment by landley** [comment]
I upgraded the kernel to 4.19 instead of a dot release.

Second commit: in theory mcm-buildall.sh builds native as well as cross toolchains. Rather than build them from source within the project, I was just going to install the existing static native compilers by extracting the tarballs from mcm.

**Comment by landley** [comment]
They were recently updated at http://b.zv.io/mcm/bin/ by the way, if you don't want to build them from source.

**Pull request closed without merging**
